# Generated by Django 5.2 on 2025-05-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=40)),
                ('apellido_doctor', models.CharField(max_length=40)),
                ('años_experiencia', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_especialidades', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=40)),
                ('apellido_paciente', models.CharField(max_length=40)),
                ('edad_paciente', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctores_especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores_especialidades', to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores_especialidades', to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api.paciente')),
            ],
        ),
    ]
